'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CustomerData
    Public Property Id As Integer
    Public Property Applicant As String
    Public Property Surname As String
    Public Property Other_Name As String
    Public Property VillageTown As String
    Public Property Address_Of_supply As String
    Public Property LGA As String
    Public Property State As String
    Public Property TelNo As String
    Public Property Alternate_No As String
    Public Property Type_Of_Premises As String
    Public Property Use_Of_Premises As String
    Public Property Name_On_The_Bill As String
    Public Property Account_Number As String
    Public Property Old_Meter_Number As String
    Public Property Tariff_Class As String
    Public Property Existing_Connection_Details As String
    Public Property Current_Billing_Information As String
    Public Property Type_Of_Connection As String
    Public Property Total_Watts As Nullable(Of Integer)
    Public Property Amounts_Purchased As Nullable(Of Integer)
    Public Property Token_Days As Nullable(Of Date)
    Public Property Grace_Value As Nullable(Of Date)
    Public Property Card_No As String
    Public Property Rate As Nullable(Of Integer)
    Public Property Area_Time_Diff As Integer
    Public Property Area As String
    Public Property Area_State_Start_Time As Nullable(Of Date)
    Public Property Area_State_End_Time As Nullable(Of Date)
    Public Property Area_State As Nullable(Of Boolean)

End Class
